/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE for Visual Studio Code Extension
 * @brief          : Main program body
 ******************************************************************************
 */

#include <stdint.h>
#include <stdio.h>       // 用于 sprintf
#include "stm32f10x.h"
#include "stm32f10x_gpio.h"
#include "stm32f10x_rcc.h"
#include "stm32f10x_adc.h"
#include "Delay.h"
#include "OLED.h"
#include "Key.h"
#include "Buzzer.h"
#include "Thermal.h"
#include "LightSensor.h"
#include "DHT11.h"
#include "MQ2.h"
#include "SERVO.h"
#include "led_pwm.h"
#include "motor.h"
#include "ESP8266.h"
#include "MenuSetting.h"
#include "MenuSelector.h"

int main(void)
{
    // 0. 初始化系统时钟和延时函数
    SystemInit();//配置系统时钟为72M	
    Delay_init(72);

    // 1. 初始化所有底层硬件
    OLED_Init();
    Key_Init();
    Buzzer_Init();
    Thermal_Init(); 
    LightSensor_Init();
    DHT11_Init();
    MQ2_Init();
    SERVO_Init();
    LED_PWM_Init();
    Motor_Init();
    ESP8266_Init();

    // 2. 初始化菜单树
    MenuInit();

    // 定义传感器数据变量
    u8 dht_temp = 0, dht_humi = 0;       // DHT11 温湿度
    float mq2_ppm = 0.0;                 // MQ2 浓度
    uint8_t light_intensity = 0;         // 光照强度
    float therm_temp = 0.0;              // 热敏温度
    
    char sendBuffer[128];                // 数据发送缓冲区
    uint16_t send_timer = 0;             // 发送频率控制定时器

    while (1) 
    {
        // === 执行后台传感器读取与仲裁任务 ===
        Run_Background_Task();

        // === ESP8266 定时数据传输逻辑 ===
        send_timer++;
        if (send_timer >= 40) // 主循环每次延时50ms，40次即为 2000ms (2秒)
        {
            send_timer = 0; // 重置定时器

            // 读取各项传感器数据
            DHT11_Read_Data(&dht_temp, &dht_humi);         // 读取 DHT11
            mq2_ppm = MQ2_GetPPM();                        // 读取 MQ2 PPM 值
            light_intensity = LightSensor_GetIntensity();  // 读取光照强度百分比
            therm_temp = Thermal_GetTemp();                // 读取热敏电阻温度

            // 将数据格式化为字符串 (这里将 float 强转为 int，避免部分 GCC 编译环境下不支持 printf 浮点数导致死机)
            // 格式示例："DHT_T:25,DHT_H:60,MQ2:120,Light:80,Therm:26\n"
            sprintf(sendBuffer, "DHT_T:%d,DHT_H:%d,MQ2:%d,Light:%d,Therm:%d\n", 
                    dht_temp, 
                    dht_humi, 
                    (int)mq2_ppm, 
                    light_intensity, 
                    (int)therm_temp);

            // 通过 ESP8266 发送数据
            ESP8266_SendData(sendBuffer);
        }

        // 3. 获取按键输入
        uint8_t key_num = Key_GetNum();

        // 4. 根据按键执行菜单操作
        if (key_num == 2) {
            SelectUP();        // SW2: 向上移动光标
        } 
        else if (key_num == 4) {
            SelectDOWN();      // SW4: 向下移动光标
        } 
        else if (key_num == 3) {
            SelectINorRUN();   // SW3: 确认 / 进入子菜单 / 执行函数
        } 
        else if (key_num == 1) {
            SelectOut();       // SW1: 返回上一级
        }

        // 5. 刷新菜单显示
        PrintSelector();

        // 6. 稍微延时，作为简单的按键防抖和控制刷新率
        Delay_ms(50); 
    }
}
