/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE for Visual Studio Code Extension
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2025 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include <stdint.h>
#include "stm32f10x.h"
#include "stm32f10x_gpio.h"
#include "stm32f10x_rcc.h"
#include "stm32f10x_adc.h"
#include "Delay.h"
#include "OLED.h"

void AD_Init(void)
{
    // 1. 开启 GPIOA 和 ADC1 的时钟
    RCC_APB2PeriphClockCmd(RCC_APB2Periph_GPIOA, ENABLE);
    RCC_APB2PeriphClockCmd(RCC_APB2Periph_ADC1, ENABLE);

    RCC_ADCCLKConfig(RCC_PCLK2_Div6);

    // 2. 配置 PA0 为模拟输入模式
    GPIO_InitTypeDef GPIO_InitStructure;
    GPIO_InitStructure.GPIO_Mode = GPIO_Mode_AIN; // 模拟输入
    GPIO_InitStructure.GPIO_Pin = GPIO_Pin_0;
    GPIO_Init(GPIOA, &GPIO_InitStructure);

    // 3. 配置 ADC1
    ADC_InitTypeDef ADC_InitStructure;
    ADC_InitStructure.ADC_Mode = ADC_Mode_Independent;                  // 独立模式
    ADC_InitStructure.ADC_ScanConvMode = DISABLE;                       // 单通道模式
    ADC_InitStructure.ADC_ContinuousConvMode = DISABLE;                 // 单次转换模式
    ADC_InitStructure.ADC_ExternalTrigConv = ADC_ExternalTrigConv_None; // 软件触发
    ADC_InitStructure.ADC_DataAlign = ADC_DataAlign_Right;              // 数据右对齐
    ADC_InitStructure.ADC_NbrOfChannel = 1;                             // 转换通道数量
    ADC_Init(ADC1, &ADC_InitStructure);

    // 4. 开启 ADC 并进行校准（标准库推荐步骤，提高精度）
    ADC_Cmd(ADC1, ENABLE);
    ADC_ResetCalibration(ADC1);
    while (ADC_GetResetCalibrationStatus(ADC1) == SET);
    ADC_StartCalibration(ADC1);
    while (ADC_GetCalibrationStatus(ADC1) == SET);
}

/* 获取 ADC 转换结果 */
uint16_t AD_GetValue(void)
{
    // 配置规则组通道：ADC1, 通道0, 序列1, 采样时间55.5个周期
    ADC_RegularChannelConfig(ADC1, ADC_Channel_0, 1, ADC_SampleTime_55Cycles5);
    
    // 触发软件转换
    ADC_SoftwareStartConvCmd(ADC1, ENABLE);
    
    // 等待转换完成标志位 (EOC)
    while (ADC_GetFlagStatus(ADC1, ADC_FLAG_EOC) == RESET);
    
    // 读取并返回结果
    return ADC_GetConversionValue(ADC1);
}

int main(void)
{
    uint16_t adc_value = 0;
    uint8_t key_num = 0;

    OLED_Init();
    AD_Init(); // 初始化 ADC

    // 显示静态文字模板
    OLED_ShowString(1, 1, "ADC Value:");
    OLED_ShowString(3, 1, "Key:");

    while (1) 
    {
        // 获取当前的 ADC 采样值
        adc_value = AD_GetValue();

        // 将 ADC 原始值显示在第一行，方便你在仿真时微调阈值
        OLED_ShowNum(1, 12, adc_value, 4);

        // 根据原理图分压计算的阈值进行判断
        if (adc_value > 3800) {
            key_num = 0; // 无按键按下 (约 4095)
        } 
        else if (adc_value < 200) {
            key_num = 1; // SW1 被按下 (直接接地，约 0)
        } 
        else if (adc_value > 500 && adc_value < 900) {
            key_num = 2; // SW2 被按下 (约 738)
        } 
        else if (adc_value > 1100 && adc_value < 1400) {
            key_num = 3; // SW3 被按下 (约 1251)
        } 
        else if (adc_value > 1700 && adc_value < 2200) {
            key_num = 4; // SW4 被按下 (约 1951)
        }

        // 显示按键状态
        if (key_num == 0) {
            OLED_ShowString(3, 6, "None "); // 加空格是为了清除残留字符
        } else {
            OLED_ShowString(3, 6, "SW  ");
            OLED_ShowNum(3, 8, key_num, 1);
        }

        // 加上适当的延时，防止屏幕刷新过快闪烁，也充当软件消抖
        Delay_ms(50);
    }
}
