/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE for Visual Studio Code Extension
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2025 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include <stdint.h>
#include "stm32f10x.h"
#include "stm32f10x_gpio.h"
#include "stm32f10x_rcc.h"
#include "stm32f10x_adc.h"
#include "Delay.h"
#include "OLED.h"
#include "Key.h"
#include "Buzzer.h"
#include "Thermal.h"
#include "LightSensor.h"



int main(void)
{
    OLED_Init();
    Thermal_Init(); 
    LightSensor_Init(); // 初始化光敏传感器

    OLED_ShowString(1, 1, "Temp:");
    OLED_ShowString(3, 1, "Light:");

    while (1) 
    {
        // === 1. 读取并显示温度 ===
        float temp = Thermal_GetTemp();
        int temp_int = (int)temp;                            
        int temp_frac = (int)((temp - temp_int) * 100);      
        
        if(temp < 0) {
            OLED_ShowChar(1, 6, '-');
            temp_int = -temp_int;
            temp_frac = -temp_frac;
        } else {
            OLED_ShowChar(1, 6, '+');
        }

        OLED_ShowNum(1, 7, temp_int, 2);       
        OLED_ShowChar(1, 9, '.');
        OLED_ShowNum(1, 10, temp_frac, 2);     
        OLED_ShowString(1, 12, " C");

        // === 2. 读取并显示光照强度 ===
        uint8_t light_percent = LightSensor_GetIntensity();
        
        OLED_ShowNum(3, 7, light_percent, 3);
        OLED_ShowChar(3, 10, '%');

        Delay_ms(100); // 延时刷新
    }
}
